/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        vex: {
          bg: '#0d1117',
          surface: '#161b22',
          border: '#30363d',
          'border-soft': '#21262d',
          'border-faint': '#1c2027',
          orange: '#f97316',
          'orange-dim': '#7c3b12',
          'orange-dark': '#ea580c',
          'orange-light': '#fbbf24',
          green: '#22c55e',
          'green-dim': '#14532d',
          'green-dark': '#16a34a',
          red: '#ef4444',
          'red-dim': '#7f1d1d',
          blue: '#3b82f6',
          'blue-light': '#79c0ff',
          purple: '#a855f7',
          'purple-dark': '#7c3aed',
          'purple-light': '#c084fc',
          text: '#e6edf3',
          'text-secondary': '#c9d1d9',
          muted: '#8b949e',
          'muted-2': '#6e7681',
          'muted-3': '#56606b',
          'muted-4': '#475059',
          'muted-5': '#3d444d',
          // editor/panel surfaces, darkest first
          panel: '#11161e',
          'panel-2': '#12161d',
          editor: '#0c1016',
          'editor-2': '#0a0e14',
        },
      },
      boxShadow: {
        'vex-card': '0 12px 30px -18px rgba(0,0,0,.8)',
        'vex-card-active': '0 18px 50px -22px rgba(249,115,22,.4), 0 8px 24px -16px rgba(0,0,0,.8)',
        'vex-glow-node': '0 0 16px rgba(249,115,22,.6)',
        'vex-glow-purple': '0 0 16px rgba(168,85,247,.6)',
        'vex-glow-logo': '0 6px 18px -6px rgba(249,115,22,.7)',
        'vex-panel': '0 18px 50px -24px rgba(0,0,0,.8)',
      },
      animation: {
        'bounce-once': 'bounce 0.5s ease 1',
        'pulse-fast': 'pulse 0.8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-in': 'slideIn 0.3s ease-out',
        'shake': 'shake 0.4s ease',
        'vd-rise': 'vdRise 0.22s ease',
        'vd-pop': 'vdPop 0.32s ease',
      },
      keyframes: {
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-6px)' },
          '40%': { transform: 'translateX(6px)' },
          '60%': { transform: 'translateX(-4px)' },
          '80%': { transform: 'translateX(4px)' },
        },
        vdRise: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        vdPop: {
          '0%': { transform: 'scale(0.7)' },
          '60%': { transform: 'scale(1.08)' },
          '100%': { transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
